// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awuamriycpisutbfuxid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3dWFtcml5Y3Bpc3V0YmZ1eGlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjAyMTMsImV4cCI6MjA2NDc5NjIxM30.rJbflKlWfB5wv_0qM5q4QVNNZOeP7nY1hFB_dQkQ3RM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});